# These are supported funding model platforms

github: [billydevyt, eddyedyt]
patreon: billydev
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: billy-s-basement.github.io
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom: ['https://billy-s-basement.gihub.io']
